version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      android-build-tooling:
        patterns:
          - "com.android.application"
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
      android-compose-ui:
        patterns:
          - "androidx.compose*"
          - "androidx.activity*"
          - "androidx.navigation*"
          - "top.yukonga.miuix.kmp:*"
    ignore:
      - dependency-name: "top.yukonga.miuix.kmp:miuix-android"
        versions:
          - ">= 0.8.0"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      ci-actions:
        patterns:
          - "actions/*"
          - "gradle/actions"
    ignore:
      - dependency-name: "gradle/actions"
        update-types:
          - "version-update:semver-major"
